### ISSUE TITLE
Using -b to select bin config name is not working.

### ISSUE THREAD

**Issue by ldzhjn** [gearnode/privatebin#9]
For example, I have a below config with "b" as bin name.
``
{
    "bin": [
        {
            "name": "b",
            "host": "https://privatebin.net"
        }
    ]
}
``

When I try to create a paste using below command
>privatebin create --bin b
>privatebin create -b b

The application shows
>Error: unknown flag: --bin
>Error: unknown shorthand flag: 'b' in -b

By the way, it works if I set the bin name to "".

**Comment by gearnode** [comment]
Fixed in the `v2.0.1`
